---
kind: pipeline
type: docker
name: default

steps:
  - name: yamllint
    image: sdesbure/yamllint
    commands:
      - yamllint -d relaxed .drone.yml
      - yamllint -d relaxed kaniko_manifest.yml

  - name: hadolint
    image: hadolint/hadolint:v1.17.6
    commands:
      - hadolint Dockerfile

  - name: gofmt
    image: golang:1.14
    commands:
      - go fmt

  - name: gotest
    depends_on:
      - gofmt
    image: golang:1.14
    commands:
      - go test

  - name: build
    depends_on:
      - gotest
    image: golang:1.14
    environment:
      CGO_ENABLED: "0"
    commands:
      - go build -o hello

  - name: run
    depends_on:
      - build
    image: alpine:3.9.6
    commands:
      - ./hello

  - name: dockerhub
    depends_on:
      - yamllint
      - hadolint
    image: plugins/docker
    settings:
      repo: hsmtkk/kaniko_demo
      username: hsmtkk
      password:
        from_secret: docker_hub_token
