apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  initContainers:
    - name: git
      image: alpine/git:v2.24.3
      args:
        - "clone"
        - "https://github.com/hsmtkk/kaniko_demo"
        - "/workspace/kaniko_demo"
      volumeMounts:
        - mountPath: /workspace
          name: workspace
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      args: ["--dockerfile=Dockerfile",
             "--context=dir:///workspace/kaniko_demo",
             "--destination=docker.io/hsmtkk/kaniko_demo"]
      volumeMounts:
        - mountPath: /workspace
          name: workspace
  restartPolicy: Never
  volumes:
    - name: workspace
      emptyDir: {}
